server:
  port: 8083

spring:
  application:
    name: springai-demo03
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${OPENAI_API_KEY} # 读环境变量

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    cn.king: debug
